language: csharp
solution: mobSocial.sln
dotnet: 4.5.1
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe
install:  
  - mono .nuget/nuget.exe restore mobSocial.sln  
script:
  - xbuild mobSocial.sln
